"use strict";
require("reflect-metadata");
require("@angular/core");
require("@angular/platform-browser-dynamic");
require("@angular/http");
require("@angular/router-deprecated");
require('zone.js/dist/zone');
require('zone.js/dist/long-stack-trace-zone');
require("rxjs");
require("jquery");
require("bootstrap");
require("pace");
require("toastr");
require("jquery-ui");
require("slimscroll");
require("bootstrap-datepicker");
require("bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min");
